--- IPC interface for communication between UI and Web processes.
--
-- In Luakit there is a single UI Lua state, but there may be multiple web
-- processes, each of which have a separate Lua state. This interface can be used
-- to communicate between the UI and web processes.
--
-- An interface similar to Luakit's signals handling is provided, and supports
-- serializing multiple Lua parameters.
--
--     -- In UI process
--     local pending = setmetatable({}, { __mode = "k" })
--     local wm = require_web_module("test_wm")
--     wm:add_web_signal("test", {
--         validate = function (_, _, text, ...) return type(text) == "string" and select("#", ...) == 0 end,
--         authorize = function (_, view) return pending[view] == true end,
--     }, function (_, view, text)
--         pending[view] = nil
--         msg.info("Web process said %s!", text)
--     end)
--
--     -- Set pending[view] = true before sending the UI request.
--
--     -- In test_wm web module
--     local ui = ipc_channel("test_wm")
--     ui:emit_signal(page, "test", "hello")
--
-- Messages support nil, booleans, finite numbers, binary strings and plain tables
-- with numeric or string keys. Argument counts and nil positions are preserved.
-- Limits are 16 MiB per message, 1 MiB per string, depth 32, and 100,000 values.
-- Web-to-UI functions and pointers are rejected. UI-to-Web messages support
-- serializable Lua functions with bounded upvalues. Tables with metatables are
-- copied as raw entries; receivers get plain tables and no metamethods run.
--
-- A loaded user web module is still an untrusted sender. Policies must check
-- exact argument types, ranges, the current document and any pending UI action.
-- Both policy callbacks receive `(channel, originating_view, ...)` and must
-- return `true`; errors and all other results reject dispatch. Validation runs
-- before authorization. Navigation, destruction and process loss invalidate
-- document generations. Context messages cannot dispatch page brokers.
--
-- @module ipc
-- @author Aidan Holm
-- @copyright 2016 Aidan Holm <aidanholm@gmail.com>

--- Open an IPC channel.
--
-- Open an IPC channel and create an `ipc_channel` object. Signals
-- emitted by the UI are delivered to web-process `add_signal()` handlers.
-- Web-process messages reach explicit UI `add_web_signal()` registrations or
-- individual `add_signal()` handlers with a third policy argument. Two-argument
-- registrations remain local and receive no renderer messages. Explicit page
-- sending is preferred; legacy sending supports declared page-ID positions and
-- scoped page callbacks. The receiving WebView always comes from WebKit.
--
-- @function ipc_channel
-- @tparam string name A name that identifies the channel.
-- @treturn ipc_channel An IPC channel endpoint object.


--- Require a Lua module on the web process.
--
-- Load the named module on all web process Lua states. The module will
-- be loaded on any future web process Lua states.
--
-- For convenience, this function returns an IPC channel with the same name as
-- the web module.
--
-- @function require_web_module
-- @tparam string name The name of the module to load.
-- @treturn ipc_channel An IPC channel endpoint object.

--- Register a local signal handler, optionally accepting renderer messages.
-- A third policy argument is UI-only. Its validate/authorize callbacks receive
-- `(channel, originating_view, ...payload)` and must return exactly true.
-- The handler keeps `(channel, ...payload)` for both local and renderer calls.
-- `policy.legacy_page_arg` optionally declares a one-based page-ID payload
-- position; the ID must equal the receiving WebView's ID. Each handler opts in
-- separately. Multiple legacy handlers must agree on the position and cannot
-- share a signal name with a modern add_web_signal registration.
-- @function ipc_channel:add_signal
-- @tparam string name Signal name.
-- @tparam function handler Existing local handler signature.
-- @tparam[opt] table policy Explicit validation and authorization policy.

--- Register a UI broker for hostile renderer messages.
-- @function ipc_channel:add_web_signal
-- @tparam string name The renderer signal name.
-- @tparam table policy Mandatory `validate` and `authorize` callbacks.
-- @tparam function handler Receives `(channel, originating_view, ...)` after both checks pass.
--
-- Use `luakit.confirm(view, operation, target)` when authorizing program launches,
-- downloaded-file opening or certificate exceptions. This displays trusted GTK
-- UI and returns true only after approval in the same document. Keep the target
-- immutable and consume pending operations before invoking privileged code.
-- Renderer navigation into internal or local-file pages also requires trusted
-- confirmation. UI-selected loads, reloads and history targets are authorized
-- for their exact destination.

-- vim: et:sw=4:ts=8:sts=4:tw=80
